name: 'bts-action'
description: 'push result of previous steps to slack'
author: 'pdotl'
inputs:
  content:
    description: 'result of previous steps'
    required: true
    default: '{}'
  run-number:
    description: 'run-id'
    default: ${{ github.run_number }}
runs:
  using: 'node12'
  main: './bts.js'